# Generated by Django 3.0 on 2019-12-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
    ]
