# Generated by Django 3.0 on 2019-12-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_remove_address_street_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'Shipping Address'), ('B', 'Billing Address')], max_length=1),
        ),
    ]
