# Generated by Django 3.0 on 2019-12-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20191215_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='payment',
        ),
    ]
