# Generated by Django 3.0 on 2019-12-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0003_auto_20191213_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='billing_Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillingAddress', to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ShippingAddress', to='addresses.Address'),
        ),
    ]
