# Generated by Django 3.0 on 2019-12-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191214_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_Address',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_Address',
            new_name='shipping_address',
        ),
    ]
