# Generated by Django 3.0 on 2019-12-12 17:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_slug'),
        ('products', '0002_auto_20191212_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=products.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='products.ProductSizes'),
        ),
    ]
