# Generated by Django 3.0 on 2019-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191212_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsizes',
            options={'verbose_name_plural': 'Product Sizes'},
        ),
        migrations.AddField(
            model_name='product',
            name='discouunt_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
