# Generated by Django 3.0 on 2019-12-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191212_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discouunt_price',
            new_name='discount_price',
        ),
    ]
